### ISSUE TITLE
Navigating to a specific header by ID seems broken

### ISSUE THREAD

**Issue by Tyrrrz** [bitwarden/passwordless-docs#47]
For example, open the following link: https://docs.passwordless.dev/guide/concepts.html#discoverable-credential

You'll see that the browser scrubs the `#...` part upon page load and stays at the beginning of the page, instead of navigating to the correct header.

**Comment by abergs** [comment]
I've spent a couple of hours trying to fix this previously, but never got it working fully! https://github.com/passwordless/docs/commit/8dfc9450e4bf694b81f58f62c899fed02fe4f283

**Comment by Tyrrrz** [comment]
Looks like it's a known issue: https://github.com/vuejs/vuepress/issues/2428

The suggested workaround seems to involve ejecting the theme, but that sounds like a nuclear approach.

**Comment by Tyrrrz** [comment]
Found a less intrusive workaround here: https://github.com/vuejs/vuepress/issues/1499#issuecomment-663807385
