### ISSUE TITLE
Wrong Status Code on /credentials/delete

### ISSUE THREAD

**Issue by fxnm** [bitwarden/passwordless-docs#84]
If you do a successful POST request on `/credentials/delete` the documentation says that it will return a `201 `or a `201`.
But you will instead receive a `204`.

Corresponding Backend Code:
https://github.com/bitwarden/passwordless-server/blob/3897af8da556e80bb6676f3f233287d49c3a03b0/src/Api/Endpoints/Credentials.cs#L17C1-L18C1

**Comment by abergs** [comment]
Thank you @fxnm, we should get this fixed in the documentation - @jonashendrickx can you change to `204` in the docs?
